#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/nconc_hists_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/nconc_hists
