#!/bin/bash

clustername=$1

i=3

outputfilename="slurm_outputs/compare_meanr_calc_methods_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/compare_meanr_calc_methods
