#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/ss_pred_vs_z_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/ss_pred_vs_z
