#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/dsd_q1_vs_q4_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/dsd_q1_vs_q4
