#!/bin/bash

clustername=$1

i=1
imax=1

while [ $imax -lt 34 ]; do
	outputfilename="slurm_outputs/imax_${imax}_lwc_spectrum_v${i}.txt"
	sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/imax_lwc_spectrum $imax
	((imax++))
done
