#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/drop_volume_cdf_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/drop_volume_cdf
