#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/combined_w_hist_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/combined_w_hist
