#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/rmax_vs_ptcount_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/rmax_vs_ptcount
