#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/check_lwc_in_slice_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/check_lwc_in_slice
