#!/bin/bash

clustername=$1

i=3

outputfilename="slurm_outputs/ss_qss_factor_correlations_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/ss_qss_factor_correlations
