#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/nolonconc_heatmap_ss_qss_vs_ss_wrf_v${i}.txt"

sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/nolonconc_heatmap_ss_qss_vs_ss_wrf
