#!/bin/bash

clustername=$1

i=2

outputfilename="slurm_outputs/hi_dsdsum_vars_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/hi_dsdsum_vars
