#!/bin/bash

clustername=$1

i=1
imax=1

while [ $imax -lt 34 ]; do
	outputfilename="slurm_outputs/imax_${imax}_heatmap_ss_qss_vs_ss_wrf_v${i}.txt"
	sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/imax_heatmap_ss_qss_vs_ss_wrf $imax
	((imax++))
done
