name: supersatenv

channels:
    - defaults
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - git
    - sphinx=2.3.0
    - matplotlib=3.1.1
    - pip
    - pip:
        - papis==0.9
