#!/bin/bash

clustername=$1
versions=( 12 )
#versions=( 1 2 3 4 5 6 7 8 9 10 11 12 )
#versions=( 13 14 15 16 17 18 19 20 21 22 23 24 )
#versions=( 25 26 27 28 29 30 31 32 33 34 35 36 )
#versions=( 37 38 39 40 41 42 43 44 45 46 47 48 )
#versions=( 3 6 9 12 )

for i in "${versions[@]}"
do
	outputfilename="slurm_outputs/heatmap_ss_qss_vs_ss_wrf_v${i}.txt"
	sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL,versionnum=$i slurm_scripts/heatmap_ss_qss_vs_ss_wrf
done
