#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/FINAL_combined_w_hist_v${i}.txt"
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/FINAL_combined_w_hist
