#!/bin/bash

clustername=$1

i=21

outputfilename="slurm_outputs/FINAL_bipanel_ss_qss_vs_z_v${i}.txt"
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/FINAL_bipanel_ss_qss_vs_z
