#!/bin/bash

clustername=$1
#versions=( 1 )
versions=( 1 2 3 4 5 6 7 8 9 10 11 12 )
#versions=( 13 14 15 16 17 18 19 20 21 22 23 24 )
#versions=( 3 6 9 12 )

for i in "${versions[@]}"
do
	outputfilename="slurm_outputs/ss_qss_hist_v${i}.txt"
	sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL,versionnum=$i slurm_scripts/ss_qss_hist
done
