#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/lwc_vs_z_v${i}.txt"
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL,versionnum=$i slurm_scripts/lwc_vs_z
