#!/bin/bash

clustername=$1
versions=( 1 2 3 7 8 9 )

for i in "${versions[@]}"
do
	outputfilename="slurm_outputs/nconc_hist_v${i}.txt"
	sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL,versionnum=$i slurm_scripts/nconc_hist
done
