#!/bin/bash

clustername=$1

i=13

outputfilename="slurm_outputs/FINAL_heatmap_ss_qss_vs_ss_wrf_v${i}.txt"
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/FINAL_heatmap_ss_qss_vs_ss_wrf
