#!/bin/bash

projdirname=20supersat
projlibname=supersatlib

function add_ref_manually {
	
	key=$1
	echo "DOI not found for $key. Please enter information manually."
	echo "Is this a journal article? [y]/n:"
	read is_journal_article
	if [ $(echo "$is_journal_article" | tr '[:upper:]' '[:lower:]') != "n" ]; then
		echo "Paper title:"
		read title
		author=''
		first_auth=true
		while true; do
			echo "Author first name:"
			read given_name
			echo "Author last name:"
			read surname
			if [ "$first_auth" == "true" ]; then
				author+="${surname}, ${given_name}"
				first_auth=false
			else
				author+=" and ${surname}, ${given_name}"
			fi
			echo "More authors? y/[n]:"
			read more_auths
			if [ $(echo "$more_auths" | tr '[:upper:]' '[:lower:]') != "y" ]; then
				break
			fi
		done
		echo "Full journal title:"
		read full_journal_title
		echo "Abbreviated journal title:"
		read abbrev_journal_title
		echo "Journal volume number:"
		read volume
		echo "Journal issue number:"
		read number
		echo "First page number:"
		read first_page
		echo "Last page number:"
		read last_page
		echo "Publication year:"
		read year
		echo "Document URL:"
		read url
		
		#dummy journal setting is for papis compatibility
		papis -l $projlibname add --batch --link ~/papers/$key \
			--folder-name $key \
			--set abbrev_journal_title $abbrev_journal_title \
			--set author $author \
			--set full_journal_title $full_journal_title \
			--set journal '' \
			--set number $number \
			--set pages $first_page-$last_page \
			--set ref ${key^} \
			--set title $title \
			--set type 'article' \
			--set url $url \
			--set volume $volume \
			--set year $year	
	else
		echo "Defaulting to book type reference. \
			Enter 'y' to continue or 'n' to skip this reference \
			(it will need to be added on the command line using papis). y/[n]:"
		read is_book
		if [ $(echo "$is_book" | tr '[:upper:]' '[:lower:]') != 'y' ]; then
			echo "Skipping reference $key"
		else
			echo "Book title:"
			read title
			author=''
			first_auth=true
			while [ $more_auths ]; do
				echo "Author first name:"
				read given_name
				echo "Author last name:"
				read surname
				if [ "$first_auth" == "true" ]; then
					author+="${surname}, ${given_name}"
					first_auth=false
				else
					author+=" and ${surname}, ${given_name}"
				fi
				echo "More authors? y/[n]:"
				read more_auths
				if [ $(echo "$more_auths" | tr '[:upper:]' '[:lower:]') != 'y' ]; then
					break
				fi
			done
			echo "Series:"
			read series
			echo "Publisher:"
			read publisher
			echo "Year of publication:"
			read year
			echo "Edition number:"
			read edition
			echo "Volume number:"
			read volume
			echo "City of publication:"
			read address
			echo "ISBN:"
			read isbn

			papis -l $projlibname add --batch --link ~/papers/$key
				 --folder-name $key \
				--set address $address \
				--set author $author \
				--set edition $edition \
				--set isbn $isbn \
				--set publisher $publisher \
				--set ref ${key^} \
				--set series $series \
				--set title $title \
				--set type 'book' \
				--set volume $volume \
				--set year $year	
		fi
	fi	
}

function update_refs {

	old_lines=$(papis -l $projlibname list --all)
	declare -a old_refs

	#get refs already in papis library database
	for line in "${old_lines[@]}"; do
		old_refs+=$(echo "$line" | rev | cut -f1 -d '/' | rev | tr '[:upper:]' '[:lower:]')
	done

	#get refs in user-edited text file
	mapfile -t new_lines < ~/proj/$projdirname/refs/refs.txt
	declare -A new_refs

	#compare old and new refs, generate array of difference between the two
	for line in "${new_lines[@]}"; do
		linearr=($line)
		ref_key=${linearr[0]}
		ref_doi=${linearr[1]}

		not_in_lib=0
		for key in "${old_refs[@]}"; do
			if [ $key==$ref_key ]; then
				not_in_lib=1
				break
			fi
		done

		if [ $not_in_lib ]; then
			new_refs[$ref_key]=$ref_doi
		fi
	done

	#add refs to library that are not already present
	for key in "${!new_refs[@]}"; do
		papis -l $projlibname add --batch --link ~/papers/$key \
			--folder-name $key \
			--from doi ${new_refs[$key]}
		if [ ! -d "./docfiles/$key" ]; then
			add_ref_manually "$key"
		fi
	done
}

update_refs
