#!/bin/bash

clustername=$1

i=1

outputfilename="slurm_outputs/uap50_compare_nconc_hist_v${i}.txt" 
sbatch -p $clustername -q lr_normal -o $outputfilename --open-mode=append --export=ALL slurm_scripts/uap50_compare_nconc_hist
